export const en = {
  common: {
    signIn: 'Sign In',
    signOut: 'Logout',
    dashboard: 'Dashboard',
    admin: 'Admin',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    save: 'Save',
    back: 'Back',
  },
  
  nav: {
    home: 'Home',
    pricing: 'Pricing',
    docs: 'Docs',
    github: 'GitHub',
  },
  
  home: {
    title: 'Deploy AI Apps in',
    titleHighlight: 'Seconds',
    subtitle: 'Upload your AI-generated app and get a live URL instantly. Works with code from Google AI Studio, ChatGPT, and more.',
    uploadTitle: 'Upload Your App',
    uploadSubtitle: 'Drag and drop your ZIP file — we\'ll auto-detect the framework',
    configureTitle: 'Configure Deployment',
    configureSubtitle: 'Choose your subdomain and add your API key',
    deployingTitle: 'Deploying Your App',
    deployingSubtitle: 'Sit back while we build and deploy your application',
    
    signInRequired: 'Sign in to deploy',
    signInMessage: 'Create a free account to start deploying your apps',
    signInButton: 'Sign in with Google',
    freeTier: 'Free tier: 5 deployments, 72-hour TTL',
    
    quotaExceeded: 'Deployment limit reached',
    quotaExceededMessage: 'You\'ve used all {max} deployment slots.',
    quotaExceededFree: ' Upgrade to Pro for more!',
    quotaExceededPro: ' Add more quota packs.',
    manageDeployments: 'Manage Deployments',
    upgradeToPro: 'Upgrade to Pro',
    
    quotaDisplay: 'Deployments: {current}/{max}',
    ttlDisplay: '{hours}h TTL',
    
    features: {
      instant: 'Instant Deploy',
      secure: 'Secure Keys',
      autoScale: 'Auto Scale',
    },
    
    supportedBy: 'Works with apps generated by',
    frameworks: 'Python (Streamlit, Gradio, Flask, FastAPI) • React • Next.js • Static HTML',
    
    footer: '© 2025 mite.now. Deploy AI apps without the hassle.',
  },
  
  login: {
    title: 'Sign in to manage your deployments',
    continueWith: 'Continue with Google',
    terms: 'By signing in, you agree to our',
    termsLink: 'Terms of Service',
    and: 'and',
    privacyLink: 'Privacy Policy',
    backToHome: '← Back to home',
  },
  
  dashboard: {
    title: 'Your Deployments',
    noDeployments: 'No deployments yet',
    noDeploymentsMessage: 'Upload your first app to get started',
    deployNow: 'Deploy Now',
    newDeployment: 'New Deployment',
    
    subscription: {
      title: 'Subscription',
      free: 'Free',
      pro: 'Pro',
      paymentDue: 'Payment Due',
      upgradeMessage: 'Upgrade to Pro for more deployments, custom domains, and database support.',
      upgradeButton: 'Upgrade to Pro - $2.99/mo',
      manageButton: 'Manage Subscription',
    },
    
    usage: {
      title: 'Usage',
      deployments: 'Deployments',
      expiresIn: '⏱️ Free deployments expire after {hours} hours',
      addQuota: 'Add 5 more (+$0.99/mo)',
    },
    
    deployment: {
      status: {
        active: 'Active',
        building: 'Building',
        failed: 'Failed',
        pending: 'Pending',
      },
      created: 'Created',
      expires: 'Expires',
      deleteConfirm: 'Are you sure you want to delete this deployment?',
    },
    
    checkout: {
      success: '🎉 Welcome to Pro! Your subscription is now active.',
      canceled: 'Checkout was canceled. You can upgrade anytime.',
    },
  },
  
  admin: {
    title: 'Admin Dashboard',
    stats: 'Statistics',
    deployments: 'Deployments',
    users: 'Users',
    revenue: 'Revenue',
    
    totalDeployments: 'Total Deployments',
    activeDeployments: 'Active',
    totalUsers: 'Total Users',
    proUsers: 'Pro Users',
    
    search: 'Search deployments...',
    filter: {
      all: 'All',
      active: 'Active',
      building: 'Building',
      failed: 'Failed',
    },
    
    deployment: {
      owner: 'Owner',
      framework: 'Framework',
      status: 'Status',
      created: 'Created',
      actions: 'Actions',
      view: 'View',
      delete: 'Delete',
    },
  },
  
  errors: {
    uploadFailed: 'Upload failed',
    deploymentFailed: 'Deployment failed',
    quotaExceeded: 'Deployment quota exceeded',
    unauthorized: 'Unauthorized',
    notFound: 'Not found',
    serverError: 'Server error',
  },
};

export type Translation = typeof en;
